### ISSUE TITLE
AlreadyDisposedException with  New UI after project start

### ISSUE THREAD

**Issue by griesi007** [drinchev/project-label#26]
I am using New UI with DataGrip. Project label triggers the attached exception after opening   a project. I am just using Label Color, no background image etc. I does not happen anytime just ocassionally. I did not find a reliable way to reproduce and force the exception. It happens randomly. 

<img width="504" alt="Screenshot 2023-09-22 092028" src="https://github.com/drinchev/project-label/assets/2854973/39944156-9407-4a45-a42d-3eaf63188fd0">

com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.ide.util.PropertiesComponent because container is already disposed (container=Project(name=PRODUCTION, containerState=DISPOSE_COMPLETED, componentStore=.....\PRODUCTION) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:695)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.projectLevelPropertiesComponent(ProjectLabelBackgroundImage.java:113)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.hideImage(ProjectLabelBackgroundImage.java:125)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.showImage(ProjectLabelBackgroundImage.java:83)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage.updateImage(ProjectLabelBackgroundImage.java:121)
	at com.drinchev.projectlabel.resources.ui.ProjectLabelBackgroundImage$1.componentMoved(ProjectLabelBackgroundImage.java:75)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:178)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:177)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:177)
	at java.desktop/java.awt.AWTEventMulticaster.componentMoved(AWTEventMulticaster.java:177)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6477)
	at java.desktop/java.awt.Component.processEvent(Component.java:6428)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Window.processEvent(Window.java:2078)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by drinchev** [comment]
Hi, I created a PR, that potentially fixes the problem. Will ping you once it's merged, to confirm if you still experience the bug.

**Comment by drinchev** [comment]
@griesi007 can you check if the latest version fixes the crash? Thanks.

**Comment by griesi007** [comment]
> @griesi007 can you check if the latest version fixes the crash? Thanks.

@drinchev yes I will tell you if it crashes again
